### ISSUE TITLE
Please add Memory Usage to the Debug Output

### ISSUE THREAD

**Issue by kutsy** [jeteokeeffe/php-cli-app-phalcon#1]
Please add Memory Usage to the Debug Output.
Wiil be nice to see:
`memory_get_usage(false)`
`memory_get_usage(true)`
`memory_get_peak_usage(false)`
`memory_get_peak_usage(true)`

**Comment by jeteokeeffe** [comment]
Great idea. I went ahead and added the memory output to the debug.

php cli.php Example cmd --debug

**Comment by jeteokeeffe** [comment]
Just to let you know, the debug info is kept in php-cli-app-phalcon/app/library/events/cli/Debug.php if you ever choose to fork or whatever and want to modify it.
