### ISSUE TITLE
undefined variable $_SERVER['USER']

### ISSUE THREAD

**Issue by mzf** [jeteokeeffe/php-cli-app-phalcon#6]
Undefined  index USER in superglobal $_SERVER
https://github.com/jeteokeeffe/php-cli-app-phalcon/blob/master/app/models/Task.php#L20

**Comment by jeteokeeffe** [comment]
What version of php are you using?

**Comment by jeteokeeffe** [comment]
can you give me the output of "php -v" and "php -i"?

**Comment by mzf** [comment]
[php -v and php -i output](https://gist.github.com/web777/8234371)

**Comment by jeteokeeffe** [comment]
Thanks, I believe I have fixed your issue.

**Comment by mzf** [comment]
Thanks! Good job
