### ISSUE TITLE
Need Info: Proper way to pass data to STDIN using Cli::Execute

### ISSUE THREAD

**Issue by jeffreycahyono** [jeteokeeffe/php-cli-app-phalcon#7]
Hi Jette,
Thanks for the high quality & reusable cli codes =)
I just wondering what is the proper way to pass data to STDIN using `Cli\Execute::execute`.
For example passing json data to the stdin of specific command like

```
echo '{"somedata":"123"}' | casperjs feeddata.js
```

**Comment by jeffreycahyono** [comment]
I've sent a PR for accomodating this issue. Pls review. 
https://github.com/jeteokeeffe/php-cli-app-phalcon/pull/8

**Comment by jeteokeeffe** [comment]
I recommend using full paths but other than that, everything looks good.

```
cat /tmp/ips 
172.24.1.5
192.168.1.22
172.24.1.6
```

```
<?php

require('Execute.php');
require('Command.php');

$cmd = "cat /tmp/ips | grep 172";

$ex = \Cli\Execute::singleton();
$ex->execute($cmd, __FILE__, __LINE__);

print_r($ex->getCommands());
?>
```
